---
name: On-push

on:
  push

jobs:
  version-check:
    uses: ./.github/workflows/vc.yaml

  conditional:
    runs-on: ubuntu-latest
    needs: version-check
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
